import { useEffect, useRef, useState } from "react";
import { PipecatClient } from "@pipecat-ai/client-js";
import { SmallWebRTCTransport } from "@pipecat-ai/small-webrtc-transport";
import { LocalMediaManager } from "./LocalMediaManager";
import {BASE,request} from "./runtimeApi";
import {useRuntimeConnection,type RuntimeEvent} from "./useRuntimeConnection";
import { Mic, Pause, Square, RotateCcw, ExternalLink, Hand, Sparkles, Trash2 } from "lucide-react";
import "./style.css";

type Speech = {text:string;utterance_id:string;generation_id:string;arm_idle:boolean};
type Draft = {id:string;revision:number;owner:string;payload:Record<string,unknown>;tool:string};
type Preferences = {speed:number;quiet:boolean;volume:number;text_size:number;high_contrast:boolean;echo_cancellation:boolean;noise_suppression:boolean;auto_gain_control:boolean};
type Snapshot = {state:string;user:{id:number;name:string;role:string}|null;draft:Draft|null;pending_request?:string|null;requested_field?:string|null;draft_labels?:Record<string,string>;preferences?:Preferences;profile?:string;profile_version?:string;receipt:Record<string,unknown>|null;errors:unknown[];diagnostics?:Record<string,unknown>;audio_connected:boolean;generation_id:string};
type Event = RuntimeEvent;
type AudioHealth={at:number;level:number;received_ms:number};
const labels:Record<string,string> = {STARTING:"Preparando los motores locales",BLOCKED:"Requiere atención",DORMANT:"Esperando que digas Gianna",INVITING:"Hablemos",WAITING_INITIAL_INPUT:"Hablemos",COLLECTING_DRAFT:"Preparando borrador",ASKING_MISSING_FIELD:"Completando tu pedido",REVIEWING_DRAFT:"Revisando",WAITING_CONFIRMATION:"Esperando tu confirmación",EXECUTING:"Guardando",RECONCILING:"Comprobando el resultado",CLOSING:"Pedido guardado",PAUSED:"Conversación en pausa",AUTH_REQUIRED:"Iniciá sesión en tickets"};
const fields:Record<string,string>={origin_unit_id:"Origen",destination_unit_id:"Destino",problem_type_id:"Tipo",description:"Descripción",note:"Nota",reason:"Motivo",status:"Estado",version:"Versión",occurred_at:"Fecha del incidente"};

export function App(){
 const [state,setState]=useState<Snapshot|null>(null),[events,setEvents]=useState<Event[]>([]),[error,setError]=useState(""),[text,setText]=useState("");
 const [connected,setConnected]=useState(false),[mic,setMic]=useState(true),[devices,setDevices]=useState<MediaDeviceInfo[]>([]),[input,setInput]=useState(""),[output,setOutput]=useState("");
 const [audioHealth,setAudioHealth]=useState<AudioHealth|null>(null),[audioNow,setAudioNow]=useState(Date.now),[audioStartedAt,setAudioStartedAt]=useState(0),[connectingAudio,setConnectingAudio]=useState(false);
 const [resetting,setResetting]=useState(false);
 const conversationVersion=useRef(0),lastResetGeneration=useRef<string|null>(null);
 const audioBusy=useRef(false),audioSession=useRef<symbol|null>(null);
 const [volume,setVolume]=useState(.85),[speed,setSpeed]=useState(1),[contrast,setContrast]=useState(false),[size,setSize]=useState(18),[quiet,setQuiet]=useState(false);
 const [aec,setAec]=useState(true),[ns,setNs]=useState(false),[agc,setAgc]=useState(false);
 const client=useRef<PipecatClient|null>(null),audio=useRef<HTMLAudioElement|null>(null),speech=useRef<Speech|null>(null),playbackTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const transcript=useRef<HTMLDivElement|null>(null),followTranscript=useRef(true);
 const preferencesActor=useRef<number|null>(null),mediaManager=useRef<LocalMediaManager|null>(null);
 const savePreference=(patch:Partial<Preferences>)=>{void request("/api/preferences",{speed,quiet,volume,text_size:size,high_contrast:contrast,echo_cancellation:aec,noise_suppression:ns,auto_gain_control:agc,...patch}).catch(e=>setError(String(e)));};
 const command=async(action:string,extra:Record<string,unknown>={})=>{const version=conversationVersion.current;try{const next=await request("/api/command",{action,...extra});if(version===conversationVersion.current){setState(next);setError("");}}catch(e){if(version===conversationVersion.current)setError(String(e));}};
 const clearDisplay=(generation:string)=>{if(lastResetGeneration.current===generation)return;lastResetGeneration.current=generation;audioSession.current=null;conversationVersion.current++;setEvents([]);setText("");setError("");speech.current=null;followTranscript.current=true;if(playbackTimer.current)clearTimeout(playbackTimer.current);if(audio.current){audio.current.pause();audio.current.srcObject=null;}setAudioHealth(null);setConnected(false);setMic(false);};
 const apply=(snapshot:Snapshot)=>{setState(previous=>({...previous,...snapshot}));const actor=snapshot.user?.id??null;if(actor!==preferencesActor.current){preferencesActor.current=actor;const p=snapshot.preferences;if(p){setSpeed(p.speed);setQuiet(p.quiet);setVolume(p.volume);setSize(p.text_size);setContrast(p.high_contrast);setAec(p.echo_cancellation);setNs(p.noise_suppression);setAgc(p.auto_gain_control);}}};
 const {connection,retry}=useRuntimeConnection<Snapshot>(apply,event=>{
  if(event.kind==="conversation_reset"){clearDisplay(String(event.data.generation_id));apply(event.data as unknown as Snapshot);}
  if(event.kind==="diagnostics")setState(previous=>previous?{...previous,diagnostics:event.data}:previous);
  if(event.kind==="state"){apply(event.data as unknown as Snapshot);if(!event.data.user)setEvents([]);}
  if(event.kind==="transcript"||event.kind==="speech"||event.kind==="receipt"||event.kind.endsWith("error"))setEvents(previous=>[...previous.slice(-39),event]);
  // A second console must not acknowledge speech playing in the microphone console.
  if(event.kind==="speech"&&event.data.silent){const m=event.data as unknown as Speech;setTimeout(()=>void request("/api/playback-complete",{utterance_id:m.utterance_id,generation_id:m.generation_id}).catch(()=>{}),200);}
 });
 useEffect(()=>{const pane=transcript.current;if(pane&&followTranscript.current)pane.scrollTop=pane.scrollHeight;},[events]);
 useEffect(()=>{if(audio.current)audio.current.volume=volume;},[volume]);
 useEffect(()=>{if(!connected)return;const timer=setInterval(()=>setAudioNow(Date.now()),500);return()=>clearInterval(timer);},[connected]);
 useEffect(()=>()=>{audioSession.current=null;void client.current?.disconnect().catch(()=>{});void mediaManager.current?.disconnect().catch(()=>{});if(playbackTimer.current)clearTimeout(playbackTimer.current);},[]);
 useEffect(()=>{document.documentElement.style.fontSize=`${size}px`;document.documentElement.dataset.contrast=String(contrast);},[size,contrast]);
 async function connect(selectedInput=input,force=false){if(audioBusy.current)return;audioBusy.current=true;setConnectingAudio(true);try{
  if(client.current?.connected&&!force&&audioHealth&&Date.now()-audioHealth.at<5000){const effective=await mediaManager.current?.configure({echoCancellation:aec,noiseSuppression:ns,autoGainControl:agc});await request("/api/audio-settings",{requested:{echoCancellation:aec,noiseSuppression:ns,autoGainControl:agc},effective});client.current.enableMic(true);setMic(true);return;}
  audioSession.current=null;
  await client.current?.disconnect().catch(()=>{});await mediaManager.current?.disconnect().catch(()=>{});
  setAudioHealth(null);setConnected(false);
  const session=Symbol();audioSession.current=session;
  const manager=new LocalMediaManager({echoCancellation:aec,noiseSuppression:ns,autoGainControl:agc},selectedInput);mediaManager.current=manager;
  const transport=new SmallWebRTCTransport({waitForICEGathering:true,iceServers:[],mediaManager:manager});
  const pc=new PipecatClient({transport,enableMic:true,enableCam:false,callbacks:{
   onConnected:()=>{if(audioSession.current===session){setConnected(true);setMic(true);const now=Date.now();setAudioStartedAt(now);setAudioNow(now);}},onDisconnected:()=>{if(audioSession.current===session){setConnected(false);setMic(false);setAudioHealth(null);}},
   onServerMessage:(message)=>{if(audioSession.current!==session)return;if(message?.kind==="speech")speech.current=message as unknown as Speech;if(message?.kind==="audio_input"){const received=message as unknown as {level:number;received_ms:number};setAudioHealth({at:Date.now(),...received});setAudioNow(Date.now());}},
   onBotStoppedSpeaking:()=>{if(audioSession.current!==session)return;const packet=speech.current;if(!packet)return;if(playbackTimer.current)clearTimeout(playbackTimer.current);
    // Transport playback + conservative local jitter/decode margin. Not a physical speaker timestamp.
    playbackTimer.current=setTimeout(()=>{if(speech.current?.utterance_id===packet.utterance_id&&audio.current&&!audio.current.paused)void request("/api/playback-complete",{utterance_id:packet.utterance_id,generation_id:packet.generation_id});},400);},
   onUserStartedSpeaking:()=>{if(audioSession.current!==session)return;if(playbackTimer.current)clearTimeout(playbackTimer.current);speech.current=null;if(audio.current)audio.current.muted=true;},
   onBotStartedSpeaking:()=>{if(audioSession.current===session&&audio.current)audio.current.muted=false;},
   onTrackStarted:(track,participant)=>{if(track.kind!=="audio")return;if(participant?.local){void request("/api/audio-settings",{requested:{echoCancellation:aec,noiseSuppression:ns,autoGainControl:agc},effective:track.getSettings()}).catch(e=>setError(String(e)));return;}
    if(audio.current){audio.current.srcObject=new MediaStream([track]);audio.current.volume=volume;void audio.current.play().catch(e=>setError("Habilitá la reproducción de audio: "+String(e)));}},
   onError:(e)=>{const detail=JSON.stringify(e);if(/TTS context|tts_unavailable/.test(detail))return;setError("Hubo un problema con el audio. Tu pedido se conserva; revisá la conexión del micrófono.");},onDeviceError:()=>setError("No pude acceder al dispositivo de audio. Revisá el micrófono elegido y los permisos del navegador.")
  }});client.current=pc;
  await pc.connect({webrtcRequestParams:{endpoint:BASE+"/api/offer"}});
  setDevices(await navigator.mediaDevices.enumerateDevices());
  setError("");
 }catch(e){await client.current?.disconnect().catch(()=>{});await mediaManager.current?.disconnect().catch(()=>{});client.current=null;setConnected(false);setMic(false);setError(String(e));}finally{audioBusy.current=false;setConnectingAudio(false);}}
 async function resetConversation(){if(resetting)return;const resumeAudio=Boolean(client.current?.connected&&mic);setResetting(true);try{const next=await request("/api/command",{action:"reset_conversation"});clearDisplay(next.generation_id);apply(next);if(resumeAudio)await connect(input,true);}catch(e){setError(String(e));}finally{setResetting(false);}}
 async function speaker(value:string){setOutput(value);const element=audio.current as HTMLAudioElement&{setSinkId?:(id:string)=>Promise<void>};try{if(element?.setSinkId)await element.setSinkId(value);else setError("Este navegador usa la salida de audio del sistema.");}catch(e){setError(String(e));}}
 const active=state?.state??"STARTING";
 const online=connection==="connected";
 const audioReceiving=connected&&audioHealth!==null&&audioNow-audioHealth.at<5000;
 const audioWaiting=connected&&!audioHealth&&audioNow-audioStartedAt<5000;
 const audioMessage=!connected?"Conectá el micrófono cuando estés listo.":!mic?"Micrófono apagado · activalo con el botón":audioWaiting?"Comprobando que llegue audio del micrófono…":!audioReceiving?"No está llegando audio. Reconectá el micrófono o elegí otra entrada.":audioHealth!.level>.006?"Audio recibido · detecto sonido":"Recibiendo audio · podés decir Gianna";
 const connectionTitle=connection==="connecting"?"Conectando con Gianna":connection==="unauthorized"?"Vinculando esta consola":"Reconectando con Gianna";
 const connectionMessage=connection==="unauthorized"?"No pude vincular esta consola. Abrí Gianna desde su dirección local y volvé a intentar.":"Estoy recuperando la conexión. Tu pedido se conserva; no se enviará ninguna acción automáticamente.";
 const failure=state?.errors.at(-1) as {message?:string;code?:string}|undefined;
 return <div className="console-shell"><aside><a href="#main" className="skip">Ir a la tarea</a><div className="brand"><Sparkles aria-hidden/> Gianna<span>Intendencia de Lavalleja</span></div><div className="profile-tag">Mesa de ayuda · IDL</div><p>Tu asistente de voz para registrar y seguir pedidos.</p><div className="account"><strong>{state?.user?.name??"Sin sesión de tickets"}</strong><small>{state?.user?.role??"Autenticación con código por correo"}</small><button className="btn btn-ghost" onClick={()=>command("logout")}>Cerrar sesión de Gianna</button></div></aside>
 <main id="main"><header><div><span className="eyebrow">ASISTENTE LOCAL</span><h1>¿En qué te ayudo?</h1></div><button className="btn btn-outline" onClick={()=>command("open_board")}><ExternalLink aria-hidden size={18}/> Abrir tickets</button></header>
 <section className="voice-card" aria-labelledby="voice-title"><div className={`orb ${audioReceiving&&mic?"connected":""}`} aria-hidden><Mic/></div><div><h2 id="voice-title">{online?(labels[active]??active):connectionTitle}</h2><p>{!online?"Esperá un momento mientras conecto la consola.":audioMessage}</p>{connected&&<meter className="microphone-level" aria-label="Nivel de audio recibido" min="0" max="1" value={mic&&audioReceiving?Math.min(1,(audioHealth?.level??0)*12):0}/>}<div role="status" aria-live={quiet?"off":"polite"}>{!online?"Conexión local":state?.pending_request?"¿Querés abrir un ticket con este problema?":state?.draft&&state.requested_field?`Completá: ${fields[state.requested_field]??state.requested_field}`:state?.draft?"Revisá el pedido antes de enviarlo":"Conversá conmigo o iniciá un nuevo ticket"}</div></div></section>
 <fieldset className="controls" disabled={!online||resetting}><button className="btn btn-primary" disabled={active==="BLOCKED"||connectingAudio} onClick={()=>void connect()}><Mic aria-hidden size={18}/>{connectingAudio?"Conectando micrófono…":connected&&!mic?"Reactivar micrófono":connected&&audioReceiving?"Micrófono conectado":audioWaiting?"Comprobando micrófono…":connected?"Reconectar micrófono":"Conectar micrófono"}</button><button className="btn" onClick={()=>command("activate")}>Activar Gianna</button><button className="btn" onClick={()=>command("pause")}><Pause aria-hidden size={18}/>Pausar conversación</button><button className="btn" onClick={()=>{client.current?.enableMic(false);setMic(false);}}>Apagar micrófono</button><button className="btn" onClick={()=>{if(playbackTimer.current)clearTimeout(playbackTimer.current);void command("stop_voice");}}><Square aria-hidden size={18}/>Detener voz</button><button className="btn" onClick={()=>command("repeat")}><RotateCcw aria-hidden size={18}/>Repetir</button></fieldset>
 {connection!=="connected"&&connection!=="connecting"&&<div className="alert" role="status"><span>{connectionMessage}</span><button className="btn btn-outline" onClick={retry}>Reintentar conexión</button></div>}
 {failure?.message&&<p className="alert alert-error" role="alert">{failure.message}</p>}
 {error&&<p className="alert alert-error" role="alert">{error}</p>}
 <fieldset className="work-grid" disabled={!online||resetting}><section className="panel"><h2>{state?.draft?"Tu pedido · Sin enviar":"Nuevo pedido"}</h2>{state?.draft?<><small>Revisión {state.draft.revision} · {state.draft.owner==="human"?"A cargo tuyo":"Sin enviar"}</small><dl>{Object.entries(state.draft.payload).map(([key,value])=><div key={key}><dt>{fields[key]??key}</dt><dd>{state.draft_labels?.[key]??String(value)}</dd></div>)}</dl><button className="btn btn-outline" onClick={()=>command("handoff")}><Hand aria-hidden size={18}/>Tomar el control manual</button><button className="btn btn-ghost" onClick={()=>command("text",{text:"Descartar borrador"})}>Descartar borrador</button></>:<div><p className="muted">{state?.pending_request??"Para registrar un problema, iniciá un ticket. Podés conversar conmigo en cualquier momento."}</p><button className="btn btn-primary" disabled={!state?.user||active==="EXECUTING"||active==="RECONCILING"} onClick={()=>command("text",{text:state?.pending_request?"Sí, registralo":"Nuevo ticket"})}>{state?.pending_request?"Abrir este ticket":"Nuevo ticket"}</button></div>}{active==="WAITING_CONFIRMATION"&&<button className="btn btn-primary" onClick={()=>command("text",{text:"Sí, es todo"})}>Confirmar y enviar</button>}{active==="RECONCILING"&&<button className="btn" onClick={()=>command("reconcile")}>Comprobar recibo</button>}{state?.receipt&&<div className="receipt"><h3>Última operación confirmada</h3><p>{String(state.receipt.code)} · Versión {String(state.receipt.version)}</p><small>Operación {String(state.receipt.operation_id)}</small></div>}</section>
 <section className="panel"><div className="conversation-heading"><h2>Conversación</h2><button type="button" className="btn btn-ghost" disabled={resetting||connectingAudio||active==="EXECUTING"||active==="RECONCILING"} onClick={()=>void resetConversation()} title="Borra el chat y el borrador sin enviar. Los tickets registrados se conservan."><Trash2 aria-hidden size={16}/>{resetting?"Borrando…":"Borrar conversación"}</button></div><div className="transcript" ref={transcript} aria-live="off" onScroll={e=>{const pane=e.currentTarget;followTranscript.current=pane.scrollHeight-pane.scrollTop-pane.clientHeight<48;}}>{events.filter(e=>e.kind==="transcript"||e.kind==="speech").slice(-8).map((e,i)=><p key={i} className={e.kind==="transcript"?"human":"assistant"}><strong>{e.kind==="transcript"?"Vos":"Gianna"}</strong>{String(e.data.text)}</p>)}</div><form onSubmit={e=>{e.preventDefault();void command("text",{text});setText("");}}><label htmlFor="command">Mensaje para Gianna</label><textarea id="command" value={text} onChange={e=>setText(e.target.value)} placeholder="Escribí lo mismo que le dirías a Gianna" maxLength={4000}/><button className="btn btn-primary" disabled={!text.trim()}>Enviar a Gianna</button><button type="button" disabled={!state?.draft} className="btn btn-ghost" onClick={()=>{setText("Corregí la descripción: ");document.getElementById("command")?.focus();}}>Corregir borrador</button></form></section></fieldset>
 <details className="panel preferences" onBlur={()=>{if(state?.user)savePreference({});}}><summary>Audio y accesibilidad</summary><div className="settings-grid"><label>Micrófono<select value={input} onChange={e=>{setInput(e.target.value);if(client.current?.connected)void connect(e.target.value,true);}}><option value="">Predeterminado</option>{devices.filter(d=>d.kind==="audioinput").map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||"Micrófono"}</option>)}</select></label><label>Salida de audio<select value={output} onChange={e=>void speaker(e.target.value)}><option value="">Predeterminada</option>{devices.filter(d=>d.kind==="audiooutput").map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||"Salida"}</option>)}</select></label><label>Volumen<input type="range" min="0" max="1" step=".05" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label><label>Velocidad de Daniela<input type="range" min=".65" max="1.4" step=".05" value={speed} onChange={e=>{setSpeed(Number(e.target.value));savePreference({speed:Number(e.target.value)});}}/></label><label>Tamaño del texto<input type="range" min="16" max="28" value={size} onChange={e=>setSize(Number(e.target.value))}/></label><label><input type="checkbox" checked={contrast} onChange={e=>setContrast(e.target.checked)}/>Alto contraste</label><label><input type="checkbox" checked={quiet} onChange={e=>{setQuiet(e.target.checked);savePreference({quiet:e.target.checked});}}/>Modo silencioso y menos anuncios</label><label><input type="checkbox" checked={aec} onChange={e=>setAec(e.target.checked)}/>Cancelación de eco</label><label><input type="checkbox" checked={ns} onChange={e=>setNs(e.target.checked)}/>Supresión de ruido del navegador</label><label><input type="checkbox" checked={agc} onChange={e=>setAgc(e.target.checked)}/>Ganancia automática</label><button className="btn" onClick={()=>command("return_to_task")}>Volver a la tarea</button></div></details>
 <details className="panel"><summary>Diagnóstico local</summary><p>Perfil: {state?.profile?`${state.profile} · ${state.profile_version}`:"Sin perfil"}. Control de escritorio, archivos, procesos y MCP: no disponibles en esta etapa.</p><pre>{JSON.stringify(state?.diagnostics,null,2)}</pre></details><button className="btn btn-ghost" onClick={()=>void request("/api/shutdown").then(()=>setError("Gianna se está cerrando.")).catch(e=>setError(String(e)))}>Cerrar Gianna</button><audio ref={audio} autoPlay aria-hidden="true"/><footer>Gianna · Mesa de ayuda <span>{audioReceiving&&mic?"Audio recibido":connected?"Sin audio recibido":"Audio desconectado"}</span></footer></main></div>;
}
