from enum import StrEnum


class State(StrEnum):
    STARTING = "STARTING"
    BLOCKED = "BLOCKED"
    DORMANT = "DORMANT"
    INVITING = "INVITING"
    WAITING_INITIAL_INPUT = "WAITING_INITIAL_INPUT"
    COLLECTING_DRAFT = "COLLECTING_DRAFT"
    ASKING_MISSING_FIELD = "ASKING_MISSING_FIELD"
    REVIEWING_DRAFT = "REVIEWING_DRAFT"
    WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
    EXECUTING = "EXECUTING"
    RECONCILING = "RECONCILING"
    CLOSING = "CLOSING"
    PAUSED = "PAUSED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
