"""initial_tickets

Revision ID: b02f44c77b22
Revises:
Create Date: 2026-10-04 03:11:37.039790

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b02f44c77b22"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "org_units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "kind", sa.Enum("area", "office", "municipality", name="unit_kind"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("can_receive_tickets", sa.Boolean(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["org_units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "problem_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=400), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("admin", "operator", "viewer", name="role"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("auth_version", sa.Integer(), nullable=False),
        sa.Column("challenge_nonce", sa.String(length=36), nullable=True),
        sa.Column(
            "last_otp_sent_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("auth_version", sa.Integer(), nullable=False),
        sa.Column(
            "expires_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=False,
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "challenges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "expires_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=False,
        ),
        sa.Column(
            "consumed_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=True,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("challenges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_challenges_user_id"), ["user_id"], unique=False)

    op.create_table(
        "idempotency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "scope", "key", name="uq_idempotency_scope"),
    )
    with op.batch_alter_table("idempotency", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_idempotency_created_at"), ["created_at"], unique=False)

    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=64), nullable=True),
        sa.Column("origin_unit_id", sa.Integer(), nullable=False),
        sa.Column("destination_unit_id", sa.Integer(), nullable=False),
        sa.Column("problem_type_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("new", "in_progress", "waiting", "resolved", "cancelled", name="ticket_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "first_response_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=True,
        ),
        sa.Column(
            "resolved_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=True,
        ),
        sa.Column(
            "cancelled_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=True,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=True,
        ),
        sa.Column(
            "archived_at",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=True,
        ),
        sa.Column("archived_by_user_id", sa.Integer(), nullable=True),
        sa.Column("archive_reason", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["archived_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_unit_id"],
            ["org_units.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_unit_id"],
            ["org_units.id"],
        ),
        sa.ForeignKeyConstraint(
            ["problem_type_id"],
            ["problem_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tickets_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tickets_destination_unit_id"), ["destination_unit_id"], unique=False
        )
        batch_op.create_index(
            "ix_tickets_operational", ["archived_at", "status", "created_at", "id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tickets_origin_unit_id"), ["origin_unit_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tickets_problem_type_id"), ["problem_type_id"], unique=False
        )

    op.create_table(
        "ticket_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql", "mariadb"),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column("actor_name", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ticket_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ticket_events_ticket_id"), ["ticket_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    for table in [
        "ticket_events",
        "tickets",
        "idempotency",
        "challenges",
        "auth_sessions",
        "users",
        "problem_types",
        "org_units",
    ]:
        op.drop_table(table)
